spring:
  datasource:
    url: jdbc:mysql://localhost:3306/learn_spring_security?useSSL=false&serverTimezone=UTC
    username: root
    password: 3306
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    serialization:
      write-dates-as-timestamps: false
  security:
    default-role: ROLE_GUEST
    default-role-hierarchy-map:
      ROLE_ADMIN:
        - ROLE_MANAGER
        - SET_ROLE_MANAGER
      ROLE_MANAGER:
        - ROLE_MEMBER
        - SET_ROLE_MEMBER
        - DELETE_MEMBER
      ROLE_MEMBER:
        - ROLE_GUEST
        - VIEW_MEMBER

server:
  port: 8081

mybatis:
  mapper-locations: "classpath*:mapper/*xml"

jwt:
  signing-key: "learn-spring-security"
  expires-in: 30
  expires-in-unit: DAYS # java.util.concurrent.TimeUnit
  authorization:
    key: "Authorization"
    value-prefix: "Bearer "