spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_example?useSSL=false&serverTimezone=UTC
    username: root
    password: 3306
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: "classpath*:mapper/*xml"